sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t makalkin/doky -f Dockerfile.dev .


script:
  - docker run -e CI=true makalkin/doky npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "doky"
  env: "Doky-env"
  bucker_name: "elasticbeanstalk-us-west-2-496574991723"
  bucket_path: "doky"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
